### ISSUE TITLE
TODO/Ideas list

### ISSUE THREAD

**Issue by joksu1234** [joksu1234/pasianssiJS#1]
**TODO**

- [x] - Moving a group of cards on the table
- [x] - Moving cards from backup deck to suit piles
- [x] - Fix "current card" indicator
- [ ] - Fix UI

**Ideas**

- [ ] - Difficulties
- [ ] - Add more animations
- [ ] - Solve button after backup deck is empty and all card's on the table are flipped
- [ ] - Drag and drop moving
